### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/office31/label2class.json'

### ISSUE THREAD

**Issue by 4Statistics** [HKUST-KnowComp/FisherDA#1]
When I run eval_da.py, 
FileNotFoundError: [Errno 2] No such file or directory: '../data/office31/label2class.json'

**Comment by ApprenticeZ** [comment]
> When I run eval_da.py,
> FileNotFoundError: [Errno 2] No such file or directory: '../data/office31/label2class.json'

Thanks for pointing the issue out. The json file is unnecessary and I've removed it.
