### ISSUE TITLE
Why the class center is a random number ?

### ISSUE THREAD

**Issue by 4Statistics** [HKUST-KnowComp/FisherDA#2]
Why the class center is a random number ?
In loss.py, line 133 
" self.centers = nn.Parameter(torch.randn(
self.num_classes, self.feat_dim).cuda()) ",

Thank you .

**Comment by ApprenticeZ** [comment]
> Why the class center is a random number ?
> In loss.py, line 133
> " self.centers = nn.Parameter(torch.randn(
> self.num_classes, self.feat_dim).cuda()) ",
> 
> Thank you .

The class centers are treated as variables and they are optimized together with other parameters in the network. They are randomly initialized in the Fisher loss. For more details, please refer to Section 3.5 (Optimization) of our paper. Thanks.
